Deus front dev
dnsenga/portfolio pull request #3
Opened 2020-06-26 15:42 UTC by dnsenga

Did substantial work on the front end (CSS) to add some animations.

2020-06-26 17:18 UTC, ElanHR commented on portfolio/src/main/webapp/index.html
> +	<li>Google, STEP Intern, Summer 2020</li>
When creating lists/blocks/tables make sure to indent child elements so it is east to tell how things are nested. 

E.g:

```
<ul>
  <li>foo</li>
  <li>bar</li>
</ul>

``` 
See: https://google.github.io/styleguide/htmlcssguide.html#General_Formatting

2020-06-26 17:20 UTC, ElanHR commented on portfolio/src/main/webapp/index.html
> +	<li>Google, STEP Intern, Summer 2020</li>
Nvm I see these have already been fixed in the followup commit. :)

2020-06-26 17:29 UTC, ElanHR commented on portfolio/src/main/webapp/index.html
> +
nit: Please delete these extra newlines.

2020-06-26 17:29 UTC, ElanHR commented on portfolio/src/main/webapp/index.html
> +
ditto

2020-06-26 17:29 UTC, ElanHR commented on portfolio/src/main/webapp/index.html
> +
ditto

2020-06-26 17:32 UTC, ElanHR commented on portfolio/src/main/webapp/index.html
> +              		<div class="period">Summer 2019</div>
these divs should align with other child elements in the same block. 

e.g.
```
<li>
  <div class="period">Summer 2019</div>
  <div class="company-role">
    <p class="company">ComzAfrica</p> 
    <p>Research and Development Intern</p>
  </div>
</li>
```

2020-06-26 17:33 UTC, ElanHR commented on portfolio/src/main/webapp/index.html
> +              		<div class="company-role">
ditto

2020-06-26 17:33 UTC, ElanHR commented on portfolio/src/main/webapp/index.html
> +              		<div class="company-role">
ditto

2020-06-26 17:42 UTC, ElanHR requested changes
Just a few comments on newlines and indentation

2020-06-26 22:20 UTC, dnsenga commented on portfolio/src/main/webapp/index.html
> +              		<div class="company-role">
Thank you

2020-06-29 17:40 UTC, ElanHR approved these changes

2020-06-29 18:22 UTC, merged